### ISSUE TITLE
cannot resume dead coroutine

### ISSUE THREAD

**Issue by ch4iril** [lewis6991/hover.nvim#2]
Please advice 
The coroutine failed
 with this message: cannot resume dead coroutine

Error executing vim.schedule lua callback: ...im/site/pack/packer/start/hover.nvim/lua/hover/async.lua:36

Thanks

**Comment by joehannes** [comment]
@ch4iril ... did you manage to solve this at all? I'm running into the same issue.

Interestingly enough, it works in lua, but my main work is ts/tsx and there I get this err ...

![image](https://user-images.githubusercontent.com/63741107/183977304-b9174750-b8b5-4570-b172-b3b1c019a957.png)

**Comment by eccentric-j** [comment]
Just installed this today to beef up the hover UI but anytime I invoke the function to show the hover card I get this error as well.

**Comment by uloco** [comment]
Same error here...

**Comment by CUexter** [comment]
how to solve this issue

**Comment by aemonge** [comment]
Same here:

![image](https://user-images.githubusercontent.com/1322348/221832113-3442a245-2790-4e40-8bdb-ce17ea209ed3.png)

Text Version:
```text
Error executing vim.schedule lua callback: ...ck/.local/share/nvim/lazy/hover.nvim/lua/hover/async.lua:37: The
 coroutine failed with this message: cannot resume dead coroutine
stack traceback:
stack traceback:
        [C]: in function 'error'
        ...ck/.local/share/nvim/lazy/hover.nvim/lua/hover/async.lua:37: in function 'done'
        ...l/share/nvim/lazy/hover.nvim/lua/hover/providers/lsp.lua:29: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1390: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
Press ENTER or type command to continue

```

My hover.nvim config

```lua
table.insert(M, {
  "lewis6991/hover.nvim",
  config = function()
    require("hover").setup {
      init = function()
      require("hover.providers.lsp")
      require('hover.providers.dictionary')
      end,
      preview_opts = {
        border = "rounded"
      },
    }

    -- Setup keymaps
    vim.keymap.set("n", "K", require("hover").hover, { desc = "hover.nvim" })
  end
})
```

Ref. https://github.com/aemonge/aemonge/tree/main/nvim

**Comment by jemag** [comment]
@lewis6991 is it possible to get more information on why this was closed? Is it related to a problem upstream?

I also encountered this issue. On my end, it would happen in markdown files once LSP started with `marksman` and `tailwindcss-language-server` installed. Removing the tailwind language server fixed the issue for me.

However, afterwards I also saw the error happen in Typescript files where both `angularls` and `tsserver` are used. Removing `angularls` fixes the problem again.

I think the issue might be related to having **more than one  language servers running on a specific file**. (null-ls does not seem to cause a problem)

**Comment by jemag** [comment]
I could try and create a repro for those multiple language server scenarios, if you want. Could post it either here or open a new issue.

**Comment by lewis6991** [comment]
Sure

**Comment by jemag** [comment]
@lewis6991 Here is the repro. The steps outlined are quite important and need to be followed as-is to reproduce.

Steps:
1. Create new folder
2. Go inside new folder
3. Initialize git repo with `git init` (important for tailwind to run later on)
4. Create following `repro.lua` file : 
```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
      "git",
      "clone",
      "--filter=blob:none",
      "--single-branch",
      "https://github.com/folke/lazy.nvim.git",
      lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
    "folke/tokyonight.nvim",
    {
        "lewis6991/hover.nvim",
        config = function()
          require("hover").setup({
              init = function()
                require("hover.providers.lsp")
                require("hover.providers.dictionary")
              end,
              preview_opts = {
                  border = nil,
              },
              preview_window = false,
              title = true,
          })
          vim.keymap.set("n", "K", require("hover").hover, { desc = "hover.nvim" })
          vim.keymap.set("n", "gK", require("hover").hover_select, { desc = "hover.nvim (select)" })
        end,
    },
    {
        "williamboman/mason.nvim",
        config = function()
          require("mason").setup()
        end,
        dependencies = {
            { "WhoIsSethDaniel/mason-tool-installer.nvim" },
        },
    },
    { "williamboman/mason-lspconfig.nvim" },
    {    "neovim/nvim-lspconfig" },
}
require("lazy").setup(plugins, {
    root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
local tools = {
    "tailwindcss-language-server",
    "marksman",
}
require("mason-lspconfig").setup()
require("mason-tool-installer").setup({
    ensure_installed = tools,
})

local lspconfig = require("lspconfig")
local installed_servers = require("mason-lspconfig").get_installed_servers()

local function setup_servers()
  for _, name in pairs(installed_servers) do
    lspconfig[name].setup({})
  end
end

setup_servers()
```
5. Create following `test.md` markdown file:
```md


Super content with great words to make a great sentence

[[ _TOC_ ]]

# Super title


Some other thing
![image](./test.png)

## Other section
Super content with great words to make a great sentence

### Another one
 Content

```
6. Open neovim once using `nvim -u repro.lua`, wait for everything to install
7. Open markdown file using `nvim -u repro.lua test.md` and wait for language servers to load
8. Ensure BOTH marksman and tailwindcss are running. In `:LspInfo`:
![image](https://user-images.githubusercontent.com/7985687/223895394-efab114f-68e5-4a3b-b544-997efb0157fd.png)
9. Pressing `K` on a bunch of words should trigger error:
![image](https://user-images.githubusercontent.com/7985687/223895569-24610ead-ed23-4a85-9c56-e962b8679ea9.png)
