### ISSUE TITLE
Make hover _not_ complain about not finding providers?

### ISSUE THREAD

**Issue by miversen33** [lewis6991/hover.nvim#25]
Basically, I just don't want to see this text when using hover.
![image](https://user-images.githubusercontent.com/2640668/219784165-974cff4d-623b-4e52-99d7-b609bca1dab9.png)

My use case, I have hover set to auto trigger on the `:CursorHold` event. Its super slick but it also means that it will attempt to run hover when there is no LSP running. Which should be fine if I have a way to tell hover to _not_ print complaints to neovim.

Looking at the source [it doesn't appear there is a way to do this currently](https://github.com/lewis6991/hover.nvim/blob/main/lua/hover/actions.lua#L176-L187)

Given that hover does allow a configuration to be passed in on setup, what's your thoughts on adding an opt in configuration that tells hover to not complain about no providers found?

I am not quite sure the best way to approach this otherwise (without undoing my current work flow which is **fine** I guess).

~~Edit: On second thought, I might be able to work around this by only triggering hover if an LSP is available for the current buffer, though I don't know a good way to establish that~~

Disregard the edit, this behavior also happens when activating on empty lines in a buffer that has an LSP attached

**Comment by lewis6991** [comment]
Closed in eb050b6b61bc70ab7271d19132e313a2269bb32e

**Comment by miversen33** [comment]
You're awesome :) Thanks!
