### ISSUE TITLE
Identifying/Customizing Highlight Group

### ISSUE THREAD

**Issue by tj-moody** [lewis6991/hover.nvim#38]
As you can see in the attached image, part of the floating window is transparent when I don't want it to be. The problem is I can't tell which highlight group this is—so far as I can tell, it's not any of the TabLine groups, which other parts of the floating window depend on, and not any of vim's default Float highlight groups, like Float, NormalFloat, FloatTitle, etc.

I'm hoping someone knows what the highlight is (my hope would be not Normal, so it can be customized separately from the editor), and it would be nice if customizing this and other highlights was possible from the config
<img width="247" alt="Screenshot 2023-09-18 at 1 40 16 PM" src="https://github.com/lewis6991/hover.nvim/assets/92702993/48e678d2-014a-4fa1-990b-9adaa0b318f7">

**Comment by willruggiano** [comment]
`:h hl-NormalFloat`
