### ISSUE TITLE
hover.hover() position is off by 1

### ISSUE THREAD

**Issue by flrgh** [lewis6991/hover.nvim#45]
Hiya :wave:

Today after updating the plugin to bb3dc1a9fa34c3577bca627b848625e94a93efe8 I noticed that `require("hover").hover()` yields a result for `$current_line + 1` instead of `$current_line`:

![Screenshot from 2023-11-11 13-49-54](https://github.com/lewis6991/hover.nvim/assets/3277009/679ac0ab-8872-4b89-9f6c-f28f89ad3eff)

![Screenshot from 2023-11-11 13-50-05](https://github.com/lewis6991/hover.nvim/assets/3277009/f42d6122-04ab-4a99-bb8e-f0da027f37d0)

Here is my lazy.nvim package def and config for `hover.nvim`:

```lua
{
  "lewis6991/hover.nvim",
  event = "VeryLazy",
  config = function()
    require("hover").setup({
      init = function()
        require("hover.providers.lsp")
        require("hover.providers.man")
        require("hover.providers.gh")
      end,
      preview_opts = {
        border = nil,
      },
      title = true,
    })
  end,
}
```

...and I have a normal mode keymap for `K` which just calls `require("hover").hover()`. I can also reproduce the problem by running this without the keymap (e.g. `:lua require("hover").hover()`).

All of my other LSP mappings (definition, declaration, code-action, etc all work normally) are working fine.

Reverting to 24369e8595736077e30b3ca5fc233f44abeccb8b fixes the problem, so I suspect that there might be some unintentional breakage from these [two recent commits](https://github.com/lewis6991/hover.nvim/compare/24369e8595736077e30b3ca5fc233f44abeccb8b...bb3dc1a9fa34c3577bca627b848625e94a93efe8)

I'll try to writeup a minimal repro config when time permits. If there's anything else I can do to help troubleshoot in the meantime, lemme know!

**Comment by lewis6991** [comment]
No repro necessary. Should be easy to fix.

**Comment by AThePeanut4** [comment]
My PR #44 fixes this.

**Comment by lewis6991** [comment]
Closed in https://github.com/lewis6991/hover.nvim/commit/3ff5bbb19f8191a77ff7fc15b8646cbd68314360
