### ISSUE TITLE
[Feature] Transform floating window to preview window

### ISSUE THREAD

**Issue by williamboman** [lewis6991/hover.nvim#5]
Hello! I personally prefer to send the contents of a floating window to a preview window, so that I can keep it open for a little while longer (and to get more [screen real estate](https://www.youtube.com/watch?v=yNxPVj0hejg) than a floating window). Do you think it'd make sense to include this an option in this plugin? I'd be happy to send a PR for it in that case. To give some idea how I'd implement it - I've currently accomplished this in my own config [like so](https://github.com/williamboman/nvim-config/blob/94c43292fc5def3afad045a595d062d4f27a9d15/lua/wb/lsp/on-attach.lua#L78-L102) (this was prior to trying hover.nvim), it's a bit messy but it works.

**Comment by lewis6991** [comment]
Sounds good to me. This would be particularly useful for the `Man` provider.
