### ISSUE TITLE
Errors with Lazy/nVim v0.9.4

### ISSUE THREAD

**Issue by savchenko** [lewis6991/hover.nvim#53]
```
E5108: Error executing lua: .../.local/share/nvim/lazy/hover.nvim/lua/hover/actions.lua:277: attempt to index field 'uv' (a nil value)
```

Is there a missing dependency, etc?

**Comment by lewis6991** [comment]
Sorry, this tracker isn't for user support.

**Comment by fredizzimo** [comment]
I think this is a bug, not a user configuration error, or request for support.

It works in Neovim nightly, but with the release 0.9.5 (and apparently also 0.9.4 as reported above), the error is printed every time the mouse is moved.

I can't find any documentation that says that this plugin requires nightly.
