### ISSUE TITLE
[Feature] Add nvim-cmp as provider

### ISSUE THREAD

**Issue by williamboman** [lewis6991/hover.nvim#6]
Me again! This is sort of in the same vein as #5 where (after 5 seconds of thinking about it) I believe this would only apply to the preview window use case. I tried to get a similar "send to preview window" functionality [submitted into nvim-cmp](https://github.com/hrsh7th/nvim-cmp/pull/1012), but at the direction of hrsh7th we decided it was out of scope. I'd be interested to know if you feel like this could have a place in this plugin? I'm not entirely sure how the integration would work as nvim-cmp manages the floating window itself, but I'm sure something could be worked out on both sides to enable this.

**Comment by lewis6991** [comment]
If it's feasible then why not. All providers are opt-in anyway. Not really sure how this would differ from the LSP provider though.

**Comment by williamboman** [comment]
I went ahead and took a look at implementing this. First impression is that it implemention-wise is pretty clunky, and would require new behaviour specific for insert mode. The use case for a cmp provider also only makes sense if you have the preview window mechanism enabled (#11), and it just overall feels like pretty weird cross-plugin integration.

I do find the idea of adding support for insert mode pretty appealing though, for things like signature hints and other LSP related hints and diagnostics. I'll close this issue though
