### ISSUE TITLE
Does not work after debugging

### ISSUE THREAD

**Issue by Green0wl** [lewis6991/hover.nvim#61]
https://github.com/lewis6991/hover.nvim/assets/72041440/01a66831-5241-4913-b871-86e8b307ef8a

**Comment by lewis6991** [comment]
¯\_(ツ)_/¯

**Comment by lewis6991** [comment]
Works for me and others.

This tracker isn't for miscellaneous user support, it's for tracking known problems. Issues that just contain a video, without any other context or documented steps to reproduce aren't acceptable. I can't help you.

**Comment by Green0wl** [comment]
thanks for the explanation. i'll send a PR soon.
