### ISSUE TITLE
LSP hover has different syntax highlighting, does not respect conceallevel for links

### ISSUE THREAD

**Issue by dlyongemallo** [lewis6991/hover.nvim#70]
The LSP hover seems to be using a different colour scheme than the editor.

For example (see the colouring of the line `import numpy as np` in the editor vs. the hover floating window):
![Screenshot from 2024-06-14 10-32-37](https://github.com/lewis6991/hover.nvim/assets/9248532/d70d75ba-85c0-42d6-b9b3-54c7fd931632)

In comparison, the default `vim.lsp.buf.hover()` uses the same colours:
![Screenshot from 2024-06-14 10-32-26](https://github.com/lewis6991/hover.nvim/assets/9248532/e2463015-b787-4195-aca4-69262b961d0b)

Furthermore, the hover doesn't respect the conceallevel for links. At `conceallevel=2`, these should be hidden unless the cursor is on the same line. The current behaviour makes markdown with URLs harder to read.

Incidentally, is there a way to fall back to the default hover (`vim.lsp.buf.hover()`) if every hover provider fails to execute? For example, what if I want to use the GitHub issues and DAP providers, but don't want to use the LSP provider? That is, I want "K" for GitHub issues and DAP expressions, but show the native LSP help.

**Comment by lewis6991** [comment]
There is no way to fallback to the default LSP hover other than copying the implementation. The current implementation is based off the old one before it got rewritten.

**Comment by dlyongemallo** [comment]
The filetype of the float window is detected as markdown. I don't understand why it isn't using the same markdown syntax highlighting which is used in the editor. Is the default syntax highlighting being overridden somehow?

**Comment by lewis6991** [comment]
Yes

**Comment by dlyongemallo** [comment]
Can you explain the reason? Is it to implement specific features? It seems strange to me not to use the same highlighting for code in the LSP floating window as in the main editor window. The identical colours are really helpful in visually pattern matching my code against the LSP help.

**Comment by lewis6991** [comment]
>  It seems strange to me not to use the same highlighting for code in the LSP floating window as in the main editor window.

It uses the exact same highlighting as Nvim 0.9 and earlier. Specifically, it calls `vim.lsp.util.convert_inpuit_to_markdown_lines()`, which is provided by Nvim's stdlib. Nvim 0.10 updated the highlighting to a new implementation that uses treesitter.

If you are still confused then I suggest you look at the code. The LSP provider is just 110 LOC.

**Comment by dlyongemallo** [comment]
Thanks, I'll work around this.
