### ISSUE TITLE
Color are off.

### ISSUE THREAD

**Issue by StephanMeijer** [lewis6991/hover.nvim#76]
There seems to be a bug or something regarding the colors when showing the hover of the LSP. Specifically the Syntax Highlighting within the hover.

```
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```

For context, I am running [AstroNvim](https://github.com/AstroNvim)

## `vim.lsp.buf.hover()`

(In WezTerm)

![image](https://github.com/user-attachments/assets/ede389e4-0af4-476b-b3b1-8478d26ba3b4)

## hover.nvim

Tried in Kitty and WezTerm. Both 

### WezTerm

<img width="2672" alt="image" src="https://github.com/user-attachments/assets/a7c36993-0fea-4900-8f83-2b120ba6b624">

### Kitty

<img width="2384" alt="image" src="https://github.com/user-attachments/assets/a3b2ae4c-5faa-4308-8047-ed1bd02ddda6">

**Comment by lewis6991** [comment]
Syntax highlighting is just different.

**Comment by StephanMeijer** [comment]
> Syntax highlighting is just different.
Not just diferent, it's inconsistent, so it seems. Why is `type` blue, but `resourceId` is gray?

**Comment by lewis6991** [comment]
`type` is a built-in function in Lua. The hover may be using vim syntax highlighting as opposed to treesitter.

**Comment by mehalter** [comment]
Yeah `vim.lsp.buf.hover()` is using treesitter in the screenshot where `hover.nvim` doesn't utilize treesitter it doesn't seem.

`vim.lsp.buf.hover()`:
![2024-09-25_19:03:57_screenshot](https://github.com/user-attachments/assets/bb70a43f-721f-450c-9a17-b1c9a2c45ceb)

going into `vim.lsp.buf.hover()` floating window and setting `conceallevel=0` to see all of the characters actually in the buffer:

![2024-09-25_19:07:37_screenshot](https://github.com/user-attachments/assets/7892a589-0870-4bb7-b3fd-e5dc680692ee)


where as `hover.nvim` has the following non-treesitter based highlighting:

![2024-09-25_19:04:08_screenshot](https://github.com/user-attachments/assets/9382b076-42f5-4bdc-92f7-1f27491b3bb7)


If I go into the buffer and set the filetype to `markdown` it does trigger treesitter, but actual markdown pieces are gone to figure out injection highlighting:

`hover.nvim` with markdown treesitter parser running on the buffer:
![2024-09-25_19:04:08_screenshot](https://github.com/user-attachments/assets/d2e05a4d-5da6-4c84-baea-9f996452a3bb)

`hover.nvim` with typescript treesitter parser enabled on the buffer:
![2024-09-25_19:07:07_screenshot](https://github.com/user-attachments/assets/fe6b742e-7cf8-4e46-875a-ce27bc1b1563)



Is it out of scope to support a similar treesitter based highlighting method for LSP hover doc?
